// <auto-generated />
using System;
using DataTransTest.Persistence.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataTransTest.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240220204916_new")]
    partial class @new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataTransTest.Domain.Entity.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "sanaa",
                            CreatedAt = new DateTime(2024, 2, 20, 23, 49, 16, 50, DateTimeKind.Local).AddTicks(5142),
                            Email = "adffaf@gmail.com",
                            FirstName = "ahmeed",
                            LastName = "ali",
                            Phone = "454646464",
                            UpdateAt = new DateTime(2024, 2, 20, 23, 49, 16, 50, DateTimeKind.Local).AddTicks(5138)
                        },
                        new
                        {
                            Id = 2,
                            Address = "sanaa",
                            CreatedAt = new DateTime(2024, 2, 20, 23, 49, 16, 50, DateTimeKind.Local).AddTicks(5146),
                            Email = "ssd2af@gmail.com",
                            FirstName = "salah",
                            LastName = "ali",
                            Phone = "454646464",
                            UpdateAt = new DateTime(2024, 2, 20, 23, 49, 16, 50, DateTimeKind.Local).AddTicks(5144)
                        },
                        new
                        {
                            Id = 3,
                            Address = "sanaa",
                            CreatedAt = new DateTime(2024, 2, 20, 23, 49, 16, 50, DateTimeKind.Local).AddTicks(5149),
                            Email = "example1@gmail.com",
                            FirstName = "hany",
                            LastName = "abdu",
                            Phone = "123456789",
                            UpdateAt = new DateTime(2024, 2, 20, 23, 49, 16, 50, DateTimeKind.Local).AddTicks(5148)
                        });
                });

            modelBuilder.Entity("DataTransTest.Domain.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DataTransTest.Domain.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "sanaa",
                            CreatedAt = new DateTime(2024, 2, 20, 23, 49, 16, 50, DateTimeKind.Local).AddTicks(9889),
                            Email = "adffaf@gmail.com",
                            FirstName = "علي",
                            LastName = "الدعيس",
                            Phone = "454646464",
                            UpdateAt = new DateTime(2024, 2, 20, 23, 49, 16, 50, DateTimeKind.Local).AddTicks(9886)
                        },
                        new
                        {
                            Id = 2,
                            Address = "sanaa",
                            CreatedAt = new DateTime(2024, 2, 20, 23, 49, 16, 50, DateTimeKind.Local).AddTicks(9895),
                            Email = "ssd2af@gmail.com",
                            FirstName = "سعيد",
                            LastName = "صالح",
                            Phone = "454646464",
                            UpdateAt = new DateTime(2024, 2, 20, 23, 49, 16, 50, DateTimeKind.Local).AddTicks(9893)
                        },
                        new
                        {
                            Id = 3,
                            Address = "sanaa",
                            CreatedAt = new DateTime(2024, 2, 20, 23, 49, 16, 50, DateTimeKind.Local).AddTicks(9898),
                            Email = "example1@gmail.com",
                            FirstName = "محمد",
                            LastName = "خالد",
                            Phone = "123456789",
                            UpdateAt = new DateTime(2024, 2, 20, 23, 49, 16, 50, DateTimeKind.Local).AddTicks(9897)
                        },
                        new
                        {
                            Id = 4,
                            Address = "sanaa",
                            CreatedAt = new DateTime(2024, 2, 20, 23, 49, 16, 50, DateTimeKind.Local).AddTicks(9901),
                            Email = "example2@gmail.com",
                            FirstName = "فاطمة",
                            LastName = "علي",
                            Phone = "987654321",
                            UpdateAt = new DateTime(2024, 2, 20, 23, 49, 16, 50, DateTimeKind.Local).AddTicks(9900)
                        },
                        new
                        {
                            Id = 5,
                            Address = "sanaa",
                            CreatedAt = new DateTime(2024, 2, 20, 23, 49, 16, 50, DateTimeKind.Local).AddTicks(9904),
                            Email = "example3@gmail.com",
                            FirstName = "أحمد",
                            LastName = "عبدالله",
                            Phone = "555555555",
                            UpdateAt = new DateTime(2024, 2, 20, 23, 49, 16, 50, DateTimeKind.Local).AddTicks(9903)
                        },
                        new
                        {
                            Id = 6,
                            Address = "sanaa",
                            CreatedAt = new DateTime(2024, 2, 20, 23, 49, 16, 50, DateTimeKind.Local).AddTicks(9907),
                            Email = "example4@gmail.com",
                            FirstName = "ريم",
                            LastName = "محمد",
                            Phone = "666666666",
                            UpdateAt = new DateTime(2024, 2, 20, 23, 49, 16, 50, DateTimeKind.Local).AddTicks(9906)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
